### PR TITLE
Fix video and audio recording, adjust volume

### PR DESCRIPTION
**Pull request by assusdan**

### CODE REVIEW

**Comment by cxldphvntxm** [comment]
1) Videorecord - work
    Audiorecord - work
2) You missed Change-ID in the commit message

**Comment by cxldphvntxm** [comment]
Close pull request. Check my message.

**Comment by assusdan** [comment]
1. Users say it doesnt. That fix improve this features.
2. Got it. Must I open new request?

**Comment by cxldphvntxm** [comment]
@assusdan :"Got it. Must I open new request?"
Yes

**Pull request closed without merging**
